services:

  # ---------- RABBITMQ ---------- #

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:4.1.0-management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    networks:
      - ecommerce-net
    healthcheck:
      test: [ "CMD", "rabbitmq-diagnostics", "ping" ]
      interval: 3s
      timeout: 3s
      retries: 3

  # ---------- AUTH-SERVICE ---------- #

  auth-service:
    container_name: auth-service
    build: ./auth-service
    command: ["python", "main.py"]
    ports:
      - "8000:8000"
    volumes:
      - ./auth-service:/auth-service
    environment:
      - DB_NAME=${AUTH_DB_NAME}
      - DB_SOCKET=auth-db:5432
      - DB_TEST_SOCKET=test-db:5432
      - DB_USER=${AUTH_DB_USER}
      - DB_PASSWORD=${AUTH_DB_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_SOCKET=rabbitmq:5672
      - JWT_TOKEN_SECRET_KEY=${JWT_TOKEN_SECRET_KEY}
      - JWT_TOKEN_ALGORITHM=${JWT_TOKEN_ALGORITHM}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES}
      - REFRESH_TOKEN_EXPIRE_DAYS=${REFRESH_TOKEN_EXPIRE_DAYS}
    depends_on:
      auth-db:
        condition: service_healthy
      test-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ecommerce-net

  auth-db:
    container_name: auth-db
    image: postgres:17.4-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./users-service/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${AUTH_DB_NAME}
      - POSTGRES_USER=${AUTH_DB_USER}
      - POSTGRES_PASSWORD=${AUTH_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${USER_DB_USER} -d ${USER_DB_NAME}'" ]
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - ecommerce-net

  # ---------- USERS-SERVICE ---------- #

  users-service:
    container_name: users-service
    build: users-service
    command: ["python", "main.py"]
    ports:
      - "8001:8000"
    volumes:
      - ./users-service:/users-service
    environment:
      - DB_NAME=${USERS_DB_NAME}
      - DB_SOCKET=users-db:5432
      - DB_TEST_SOCKET=test-db:5432
      - DB_USER=${USERS_DB_USER}
      - DB_PASSWORD=${USERS_DB_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_SOCKET=rabbitmq:5672
    depends_on:
      user-db:
        condition: service_healthy
      test-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ecommerce-net

  users-worker:
    container_name: users-worker
    build: users-service
    command: ["python", "worker.py"]
    volumes:
      - ./users-service:/users-service
    environment:
      - DB_NAME=${USERS_DB_NAME}
      - DB_SOCKET=users-db:5432
      - DB_TEST_SOCKET=test-db:5432
      - DB_USER=${USERS_DB_USER}
      - DB_PASSWORD=${USERS_DB_PASSWORD}
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_SOCKET=rabbitmq:5672
    depends_on:
      user-db:
        condition: service_healthy
      test-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - ecommerce-net

  users-db:
    container_name: users-db
    image: postgres:17.4-alpine
    ports:
      - "5433:5432"
    volumes:
      - ./users-service/data/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${USERS_DB_NAME}
      - POSTGRES_USER=${USERS_DB_USER}
      - POSTGRES_PASSWORD=${USERS_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${USER_DB_USER} -d ${USER_DB_NAME}'" ]
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - ecommerce-net


  # ---------- TEST-DATABASE ---------- #
  
  test-db:
    container_name: test-db
    image: postgres:17.4-alpine
    ports:
      - "5434:5432"
    environment:
      - POSTGRES_DB=${USERS_DB_NAME}
      - POSTGRES_USER=${USERS_DB_USER}
      - POSTGRES_PASSWORD=${USERS_DB_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "sh -c 'pg_isready -U ${USERS_DB_USER} -d ${USERS_DB_NAME}'" ]
      interval: 3s
      timeout: 3s
      retries: 3
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true
