services:
  email-worker:
    container_name: email-worker
    build:
      context: .
      dockerfile: microservices/email/Dockerfile-worker
    image: email-worker:0.1
    command: ["python", "worker.py"]
    volumes:
      - ./microservices/email:/email
      - ./core:/email/core
    environment:
      - RABBITMQ_NAME=email-worker
      - RABBITMQ_USER=${RABBITMQ_USER}
      - RABBITMQ_PASSWORD=${RABBITMQ_PASSWORD}
      - RABBITMQ_SOCKET=rabbitmq:5672
      - DEFAULT_FROM_EMAIL=${DEFAULT_FROM_EMAIL}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
      - SENDGRID_API_URL=${SENDGRID_API_URL}
      - RESET_PASSWORD_URL=${RESET_PASSWORD_URL}
    networks:
      - ecommerce-net

  postfix:
    image: boky/postfix:latest-alpine
    container_name: postfix
    hostname: postfix
    environment:
      - RELAYHOST=[smtp.sendgrid.net]:587
      - RELAYHOST_USERNAME=${RELAYHOST_USERNAME}
      - RELAYHOST_PASSWORD=${RELAYHOST_PASSWORD}
      - ALLOWED_SENDER_DOMAINS=gmail.com
      - POSTFIX_smtp_tls_security_level=encrypt
    ports:
      - "587:587"
    networks:
      - ecommerce-net

networks:
  ecommerce-net:
    external: true