http:
  routers:
    auth:
      rule: "Host(`auth.localhost`)"
      service: auth
      entryPoints:
        - web

  services:
    auth:
      loadBalancer:
        servers:
          - url: "http://auth-service:8000"
