http:
  middlewares:
#    realip:
#      headers:
#        customRequestHeaders:
#          X-Forwarded-For: "{clientIP}"

    auth:
      forwardAuth:
        address: "http://auth-service:8000/api/v1/auth/authenticate"
        trustForwardHeader: true
        authResponseHeaders:
          - X-User-Id
