http:
  routers:
    users:
      rule: "Host(`users.localhost`)"
      service: users
      entryPoints:
        - web
      priority: 10
#      middlewares:
#        - realip

    users-private:
      rule: "Host(`users.localhost`) && Path(`/api/v1/users/me`)"
      service: users
      entryPoints:
        - web
      priority: 100
      middlewares:
#        - realip
        - auth

  services:
    users:
      loadBalancer:
        servers:
          - url: "http://users-service:8000"
