FROM python:3.13-alpine
LABEL authors="nero"

WORKDIR /users

COPY /microservices/users/requirements.txt /users

RUN pip install --no-cache-dir -r requirements.txt

COPY /microservices/users /users
COPY /core /users/core

RUN apk add --no-cache gcc musl-dev libffi-dev

EXPOSE 8000

ENV PYTHONPATH=/users
